### ISSUE TITLE
Add a Requirements PIP File for Managing Dependencies

### ISSUE THREAD

**Issue by Alex92rus** [rbaltrusch/desktop_shop#1]
Declare all necessary dependencies for the project.

Consider using the more advanced PIPfile:

[https://github.com/pypa/pipfile](https://github.com/pypa/pipfile)
[https://packaging.python.org/tutorials/managing-dependencies/](https://packaging.python.org/tutorials/managing-dependencies/)

Alternatively generate the traditional requirements.txt file. For Python 3 use below:

pip3 freeze > requirements.txt

**Comment by rbaltrusch** [comment]
Thanks, added requirements.txt, issue can be closed.
